export const FETCH_ESTATE = 'FETCH_ESTATE';
export const CREATE_ESTATE = 'CREATE_ESTATE';
export const UPDATE_ESTATE = 'UPDATE_ESTATE';
export const DELETE_ESTATE = 'DELETE_ESTATE';
export const FETCH_ESTATE_BY_SEARCH = 'FETCH_ESTATE_BY_SEARCH';
